#pragma once

#include <mana/core/corecommon.h>
#include <mana/core/input/controllers/controller.h>
#include <mana/core/math/quatd.h>
#include <mana/core/math/vec3d.h>

// TODO: This will have to be moved to a file for default loading

#define TOTAL_DRIVINGML_ACTIONS 32

global const u8 PLAYER_CONTROLLER_DEFAULT_GAMECUBE_BINDINGS[TOTAL_DRIVINGML_ACTIONS + 1] = {
    GC_CONTROLLER_ACTION_JOYSTICK_Y,
    GC_CONTROLLER_ACTION_JOYSTICK_Y,
    GC_CONTROLLER_ACTION_JOYSTICK_X,
    GC_CONTROLLER_ACTION_JOYSTICK_X,
    GC_CONTROLLER_ACTION_CSTICK_Y,
    GC_CONTROLLER_ACTION_CSTICK_Y,
    GC_CONTROLLER_ACTION_CSTICK_X,
    GC_CONTROLLER_ACTION_CSTICK_X,
    GC_CONTROLLER_ACTION_A,
    GC_CONTROLLER_ACTION_Y,
    GC_CONTROLLER_ACTION_B,
    GC_CONTROLLER_ACTION_X,
    GC_CONTROLLER_ACTION_L_TRIGGER,
    GC_CONTROLLER_ACTION_R_TRIGGER,
    GC_CONTROLLER_ACTION_DPAD_DOWN,
    GC_CONTROLLER_ACTION_Z,
    GC_CONTROLLER_ACTION_START,
    GC_CONTROLLER_ACTION_DPAD_UP,
    GC_CONTROLLER_ACTION_DPAD_LEFT,
    GC_CONTROLLER_ACTION_DPAD_RIGHT,
    GC_CONTROLLER_ACTION_LAST,
    GC_CONTROLLER_ACTION_LAST,
    GC_CONTROLLER_ACTION_LAST,
    GC_CONTROLLER_ACTION_LAST,
    GC_CONTROLLER_ACTION_LAST,
    GC_CONTROLLER_ACTION_LAST,
    GC_CONTROLLER_ACTION_LAST,
    GC_CONTROLLER_ACTION_LAST,
    GC_CONTROLLER_ACTION_LAST,
    GC_CONTROLLER_ACTION_LAST,
    GC_CONTROLLER_ACTION_LAST,
    GC_CONTROLLER_ACTION_LAST,
    GC_CONTROLLER_ACTION_LAST,
};

/*global const unint_fast8_t PLAYER_CONTROLLER_DEFAULT_KEYBOARD_BINDINGS[TOTAL_DRIVINGML_ACTIONS + 1] = {
    KB_CONTROLLER_ACTION_W,
    KB_CONTROLLER_ACTION_S,
    KB_CONTROLLER_ACTION_A,
    KB_CONTROLLER_ACTION_D,
    KB_CONTROLLER_ACTION_UP,
    KB_CONTROLLER_ACTION_DOWN,
    KB_CONTROLLER_ACTION_LEFT,
    KB_CONTROLLER_ACTION_RIGHT,
    KB_CONTROLLER_ACTION_E,
    KB_CONTROLLER_ACTION_SPACE,
    KB_CONTROLLER_ACTION_LSHIFT,
    KB_CONTROLLER_ACTION_LCTRL,
    KB_CONTROLLER_ACTION_LMOUSE,
    KB_CONTROLLER_ACTION_RMOUSE,
    KB_CONTROLLER_ACTION_F,
    KB_CONTROLLER_ACTION_Z,
    KB_CONTROLLER_ACTION_ESCAPE,
    KB_CONTROLLER_ACTION_1,
    KB_CONTROLLER_ACTION_2,
    KB_CONTROLLER_ACTION_3,
    KB_CONTROLLER_ACTION_4,
    KB_CONTROLLER_ACTION_5,
    KB_CONTROLLER_ACTION_6,
    KB_CONTROLLER_ACTION_7,
    KB_CONTROLLER_ACTION_8,
    KB_CONTROLLER_ACTION_9,
    KB_CONTROLLER_ACTION_0};*/

// Define actions
enum PLAYER_CONTROLLER_ACTION {
  PLAYER_CONTROLLER_MOVE_FORWARD = 0,
  PLAYER_CONTROLLER_MOVE_BACKWARD,
  PLAYER_CONTROLLER_MOVE_LEFT,
  PLAYER_CONTROLLER_MOVE_RIGHT,
  PLAYER_CONTROLLER_CAMERA_UP,
  PLAYER_CONTROLLER_CAMERA_DOWN,
  PLAYER_CONTROLLER_CAMERA_LEFT,
  PLAYER_CONTROLLER_CAMERA_RIGHT,
  PLAYER_CONTROLLER_INTERACT,
  PLAYER_CONTROLLER_JUMP,
  PLAYER_CONTROLLER_SPRINT,
  PLAYER_CONTROLLER_CROUCH,
  PLAYER_CONTROLLER_LEFT_ATTACK,
  PLAYER_CONTROLLER_RIGHT_ATTACK,
  PLAYER_CONTROLLER_PUT_AWAY_WEAPONS,
  PLAYER_CONTROLLER_PHYSICS_GRAB,
  PLAYER_CONTROLLER_GAME_MENU,
  PLAYER_CONTROLLER_PLAYER_MENU,
  PLAYER_CONTROLLER_FAVORITES_MENU,
  PLAYER_CONTROLLER_CAMERA_CHANGE,
  PLAYER_CONTROLLER_AUTO_RUN,
  PLAYER_CONTROLLER_WALK,
  PLAYER_CONTROLLER_CHAT,
  PLAYER_CONTROLLER_HOTKEY_1,
  PLAYER_CONTROLLER_HOTKEY_2,
  PLAYER_CONTROLLER_HOTKEY_3,
  PLAYER_CONTROLLER_HOTKEY_4,
  PLAYER_CONTROLLER_HOTKEY_5,
  PLAYER_CONTROLLER_HOTKEY_6,
  PLAYER_CONTROLLER_HOTKEY_7,
  PLAYER_CONTROLLER_HOTKEY_8,
  PLAYER_CONTROLLER_HOTKEY_9,
  PLAYER_CONTROLLER_LAST
};

struct PlayerController {
  vec3d pos;
  quatd rot;

  // Selected primary controller but can recieve bindings from any controller, should be switchable
  struct Controller* primary_controller;
  enum PLAYER_CONTROLLER_ACTION input_to_actions_map_main[PLAYER_CONTROLLER_LAST];
  enum PLAYER_CONTROLLER_ACTION input_to_actions_map_alt[PLAYER_CONTROLLER_LAST];
};

void player_controller_init(struct PlayerController* player_controller);
void player_controller_delete(struct PlayerController* player_controller);
// Should action and value
void player_controller_process_input(struct PlayerController* player_controller, struct ControllerAction* controller_action_list, u8 controller_action_list_size);
